title: Adrien Ruggiero
logo: "/images/photo_CV.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionné par l’intelligence artificielle et les sciences des données, j’ai pour ambition de devenir data scientist. J'adore m'investir dans des projets de data science sur des projets qui m'intéressent.
  <br><br>
  
  <a href="https://www.linkedin.com/in/adrien-ruggiero/">Mon profil LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
