title: Adrien Ruggiero
logo: "/images/photo_CV.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Artificial intelligence and data science enthusiasts, my ambition is to become a data scientist. I love to get involved in data science projects on projects that interest me.
  <br><br>
  
  <a href="https://www.linkedin.com/in/adrien-ruggiero/">View my LinkedIn profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
