title: Adrien Ruggiero
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionné par l’intelligence artificielle et les sciences des données, j’ai pour ambition de devenir data scientist. Les divers projets et
  expériences professionnelles que j’ai pu mener dans ce domaine ont été un réel plaisir pour moi. Je recherche donc un stage de fin
  d’étude de 6 mois à partir de mars 2023 afin de poursuivre la réalisation mon projet professionnel. Je suis une personne
  impliquée, dynamique et entreprenante et je n’hésiterai pas à tirer profit de ce stage pour enrichir mon panel de compétences et
  pour relever de nouveaux challenges dans un domaine qui me fascine depuis le lycée.
  <br><br>
  
  <a href="https://www.linkedin.com/in/adrien-ruggiero/">Mon profil LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
